apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64, /9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMHEBMTEhMSFRIVEhATEhcYFRUQFhISFxIXFhYXFhUYHSggGBolGxUTITEhJikrLi4uFx8zODMsOCg5LjcBCgoKDg0OGxAQGy0lICM3Ly0tLSstLTAtMS8tNy0tLS0vLS0tLzAtLS0tLS8tLy0tLS0tLS0tLS4tLS0tLS0tLf/AABEIAOAA4AMBEQACEQEDEQH/xAAcAAEAAgIDAQAAAAAAAAAAAAAABgcBBQIDBAj/xABBEAACAQEEBgUJBwIGAwAAAAAAAQIDBAUREwYSITFBUQdhcYGRFDI1UnOSsbPBFSIjQnKh0WKCM1OissLhFjRD/8QAGgEBAAMBAQEAAAAAAAAAAAAAAAQFBgMBAv/EADURAQABAwICBgoCAQUBAAAAAAABAgMRBAUhMRJBUXGRsRMiMjM0YYGh0eHB8EIUIyRy8YL/2gAMAwEAAhEDEQA/ALxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4VaiorGTSS4t4I+a66aIzVOIe00zVOIhqLVpJTpbIJzfux8X/BVXt4tUcLcdKfCPH9J1vb7lXtcGrr6RVam7Vj2LF+LK25u2oq9nEfdMo0FqOeZeOpedWpvqT8cPgRK9XqK+dc+OPJ3jT245Uw6ZWhy3yk+9nCaqp5zPjL7iiI6iNolHdKS72IqqjlM+Mk0RPU7qd51ae6pPxx+J3o1eoo5Vz4583xOntzzph7KGkVWnv1ZdqwfiiXb3bUU+1ifs4V6C1PLMNpZdJKdXZNOD96Piv4LKxvFqvhcjoz4x4/pDubfcp9ni29Koqyxi00+KeKLWiumuM0zmEGqmaZxMOZ9PAAAAAAAAAAAAAAAAAAbgI9emk0aGMaWE5cZflXZ6xUardaaPVtcZ7er9rKxt9VXG5wjs6/0jNqts7W9acnJ8Mdy7FwKG7drvVdK5OVrbtU24xTGHVmHPD7wZgwYMwYMGYMGDMGDBmDBgzBgwZgwYdtlts7I9aEnF8cNz7VxOlq7XZq6VucPi5apuRiqMpNdek0a+EauEJcJflfb6pfaXdaa/Vu8J7er9Kq/t9VPG3xjs6/2kO8t1aAAAAAAAAAAAAAAAddetGzxcpNKKWLb2JI+a66aImqqcRD6ppmqejTHFBb80hleLcYYxpctzn+rkuozms11V/wBWnhT59/4X2l0VNr1quNXk0+YV+E3BmDBgzBgwZgwYMwYMGYMGDMGDBmDBgzBgwZgwYMwYMGYMGG4uPSGV3NRnjKly3uH6ea6iw0euqserVxp8u78IWq0VN31qeFXmnVCtG0RUotOLWKa2po0dFdNcRVTOYlQ1UzTPRqji7D6fIAAAAAAAAAAAONSappttJJNtvYkkeTMRGZexEzOIVxpHfzvaeEcVRi/ur1n60vouBm9Zqpv1Yj2Y5fP5tHo9JFinM+1PP8NRmELCZgzBgwZgwYMwYMGYMGDMGDDDqpcRwe9EVVPiOB0WcwYeYMwYMGYMGDMGDBmDBgzBgw2+jl/O6Z4SxdGT+8vVfrR+q4k3R6qbFWJ9mefy+aHrNJF+nMe1HL8LHpzVRJppppNNbU0zSRMTGYZyYmJxLkevAAAAAAAAAAAgund+a0vJoPYsHWfN71D6vuKfcdRn/ap+v4Xm2aXEemq+n5Q7MKnC3wZgw9wZgwYMwYMDqYDBhIbo0Ur3ilKX4UHxksZNdUP5Jtnb7lzjPCPv4K+/uFq1wj1p+XLxSqxaIWazedGVR85vZ7q2Fnb26zTzjPeqrm5X6+U47m1pXXRo+bSpr+yP8EmLFuOVMeCLVfu1c6p8SrddCt51Km/7I/wJsW550x4FN+7Tyqnxaq26H2a0+apU3zi9nuvYRbm3WauUY7ku3uV+jnOe9FL30Vr3cnKP4sFvcVhJLrht/bErb233LfGOMfL8LSxuFq7wn1Z+f5R9VMSFhYYMwYMGYMGDMGDBmDDzCY6CX5qy8mm9jxdF8nvcPqu8ttu1GP8Aaq+n4VG56XMemp+v5TouFGAAAAAAAAANbpDeiuezzq7G0sILnN7IrxON+76K3NSRpbE37sUePcp6VZzbcnjJtuTe9tvFvxM3PHjLXRTERiGMwYMGYMGDMGDDlTxqyUYpylJpRS2tt7kj2KZmcQ8nERmeSytFtFI3alUrYTrbGuMaXVHm+vwLrS6Km361XGfJndbuFV31KOFPn/exKCerAAAAAAItpTonG8U6tHCNba2t0avbyl1+JA1Wii561HCfNZ6LcJtepc40+StajdNuMk1JNqSexpremikmmYnEtHGJjMMZgwYMwYMGYMGGY1nBpxeEk04tb008U13iOHGCaYmMSuHR69FfFnhV2JtYTXKa2SXiaSxd9LbipkdVYmxdmjw7myOyOAAAAAAAAVp0nXpm16dBP7tOOvLrnLYvCOPvFTuFeaoo7Gi2exi3Nyevh9I/v2QzMK/C4wZgwYMwYMGYMGFk9HlweT01aai/Emvwk/yU3x7ZfDAttFp+jHTq5yzu6avpVehp5Rz+c/pNSwU4BhvA8mYjjJzeSpelGnvqR7tvwIle4aajhNcJFOlu1cqWKd7UZ/8A0j37PieU7jpquVcE6W9H+L2RkpLFPFeJMiYmMw4TExwlk9eAEI6RLgz4O1U19+C/FS/PTX5u2Pw7Cv12n6Uekp5xzXO1avo1ehr5Ty+U/tXGYVOGhwZgwYMwYMGYMGEz6Mb0yq1Sg392pHXh1TjsfjHD3Sw2+vFU0dqn3ixm3FyOrh9J/v3WWWzOgAAAAAAAFBXzeP2laK1XhOpJx/SnhH9kiguVdOuau1t7Fn0Vqmjsj/148w54dsGYMGDMGDDbaLXZ9t2unSfmYudT2cdrXfsXedrFr0lcQi6y/wCgszXHPlHevJLDcXrGMgeO8rwjYI4vbJ+bHn/CIes1tGmpzPGZ5R/ep3saeq7OI5dcotbLbO2v772cFuiu4ymp1V3UTm5PDs6vBdWrNFqPVj69bzEd1ZA7rJap2R4weHNcH2o7WNRcsTm3OPLwc7lqi5GKoSi67yjb1ymt6+q6jVaHX06mnsqjnH4U2o002p7Ye8nozElrLB7U9j60CJwovSa7fsS1VKK81PWp+zltiu7au4or9r0dc0tppL/p7MV9fX3tXmHHCTgzBgwZgwYey5rx+zbRRq8IVIuX6ccJfs2dLdXQrirscb9n0tqqjtj/AMX6X7EAAAAAAANdpDavIrJXqerRqNduq8D4uTiiZd9LR071NPbMPnyEtRJckkUeG6njOXLXGHmDXGDBrjBhZHQ7ZNbymu+dOjHuTnP/AHQ8Cw0NHOpn99uexb75/iPKVlE9n3GrUVKLk9yTb7EfNdcUUzVVyh7TTNU4hCrXaXa5ucuO5clwRiNRfqv3JuVdf2jsaG1bi3TFMOk4ugAAAc6FZ2eSlHeniv4fUfdq7VariujnD4roiumaZ5SmtmrK0QjJbmkzb2bsXbcV08pZ+5RNFU0z1O06vhWfTFZNR2asuOZRl4KcPhU8SBraOVTQ7FczFdvun+J/hXOuV+F/g1xgwa4wYcZy1k1zTQw9jhOX0Jo9avLbJQqetRpt9uqsS8tzmiJYXU0dC9VT2TLYH24AAAAAAR3pDnqXZavZNeLSOV/3cp+2RnVUd6hcwqcNpgzBgwZgwYMwYMLn6I4at3KXrVqz8Jav0LLSxi2yW9T/AMrHZEJqSVS1mkVXLoNes4x+v0Kzd7nR00x24hM0NObuexFTJroAAAAACS6M1dalKPqyfg1j/JptludKzNPZPnxVG4U4uRPbDcFygIR0vQ1rvx9WvRfi3H6kbVRm2t9kn/k47YlTWYVuGswZgwYMwYMGYMGF9dHs9e7LL7JLwbRbWPdwxW5xjV196RHVBAAAAAAjnSJDXuu1dVJvwaOV73cp22TjVUd75/KttwAAAvHol9F0/aV/mMstN7tj95+LnujyTI7qpqdJY40V1Tj9V9So3qM6fPZMJ2gn/d+iMGXXAAAAAAEi0WjhCb5yS8F/2aPY6f8Abrq+flCq3GfWphuy8VyDdMVbLu5L169JLuxl/wAWR9VPqLjZKc6nPZEqVK5rQAAA+gOjyGpddl9kn4tlpZ93DEbnOdVX3pGdUEAAAAADW6SWXy2x2in61Gql26rw/c+K4zTMO+lr6F6irsmHzbF4pdiKlvpZAAALx6JfRdP2lf5jLLTe7Y/efi57o8kyO6qee32fyqnKHNbO3gR9VZ9Naqt9rrZuejripCmnHY1g1sa5PiYiYmOE82gzE8YA9AAADAEzuqzeSUoxe/fLte02mhsegsU0Tz5z3yoNTc9JcmqHrJbgqnprt+tOzUE9yqVZ9rwjD/mQtXVyhpNhtYiu5Pyj+Z/hWRDaEAAYk8E+xgh9JaN2XyKx2en6tGkn26qx/ctqIxTEMDqq+nerq7Zlsj7cAAAAAAAHzXf93/ZNqr0eFOrNR/Q3jD/S0VNdPRqmG+01301mm52x9+t4D4dwABePRL6Lp+0r/MZZab3bH7z8XPdHkmR3VQBo78up1XmU1i/zR59a6yi3Pbprn0tqOPXHb84+fmsdJqopjoV8uqUdM6tWQAGHsPBvrjup4qpUWGG2EXvx5sv9s26cxeux3R/M/wAK3V6qMdCj6ykBoVW41KipRcpNKKTbb2JJLFth7ETM4h856UXw7+tdWvt1ZSwpp8KUdkP2295VXK+nVMt3pNP/AKezTb6459/W1RzSQAB77gu/7WtVCjwqVYKX6E8Z/wClM+6KelVEOGpu+hs1XOyPv1PpQtmBAAAAAAAAKg6Zbp8ntFK0xX3ascub5VIbY49sW/dZB1VGJipqNjv9K3Vanq4x3T/fursiL0AAXj0S+i6ftK/zGWWm92x+8/Fz3R5Jkd1UAAPDbbqp2za1hL1lsffzIOp2+zf41Rie2Ei1qrlvhHLslq6mjkl5tRNdcWvgyqr2OvPq1x9Y/abTuNPXT92IaOSe+pFdkW/izynY7mfWrj6R+ydxp6qZbOxXRTsrxw1pc5bcOxbkWmm2yxYnOMz2yiXdXcucOUfJsCwRQCseljStQi7FRacpf+zJfljvVNdb3vku0h6m7/hH1aHZtDmfT1//AD+VVEJpAAAAsToaunyi0VbTJfdpRy4PnUntlh2RS95EvS0ZmalFvl/o26bUdfGe6P79lvk5lwAAAAAAADT6WXKtILJUoPBSaxpt/lqR2xfj8T4uUdOnCVo9TOnvRc8e587VKboylGScZRk4yT3xkng0+xplVMYbqJiYzHKXE8egF49Evoun7Sv8xllpvdsfvPxc90eSZHdVOi12ynYoqVScYRcoxTk8FrSeEVj1s8mYjm+6LdVc4pjLvPXwAAAAABXenPSJCxKVCxyU6zxU6q2wpfp4Sn+yIt7URHCnmvdv2mquYuXoxT2dc/iFQyk5tttttttt4tt7W2+LIDTxGOEMB6AAOVOm60oxinKUpKMUt8pN4JLtbR7EZeTMRGZ5Q+idE7lWj9kp0Fg5JY1GvzVJbZPx+Ba26OhThhdZqZ1F6bnh3NwfaKAAAAAAAAAKo6W9F3Tl5bSj914K0JcHujU7OD7iFqbX+cNLsutzHoK5/wCv4/CsiG0IBeXRL6Lp+0r/ADGWWm92x29fFz3R5Jkd1UhvS16Lqe0ofMRw1Pu1rs3xcd0+StNG9OrXcCUFJVaSwSp1G3qrlGW+PZtRDt36qODQarbLGonpTGJ7Y/mFg3V0qWS1JZ0alCXHFZsMeqcfqkSqdVRPPgo72yX6PYmKo8J8G/o6ZWCvutVHvlg/3OsXaJ60Krb9TTzokr6ZWChvtVHulrPwQm7RHWU7fqauVEo/evSpZLKnkxqV5cMFlQ75S2+CZyq1VEcuKdZ2O/X7cxTHjPgr7STTm13+nCUlSovFOnTxSkuU5b5dmxEW5fqr4LvS7ZY089KIzPbP8IzuOKxAAAABZvRJou6kvLasfurFWdPi90qnZwXeTNNa/wA5+jPb1rcR6Cif+34/K1yazQAAAAAAAAAAcKtJVouMknGSakntTT2NNDm9iZpnMKK080PlozU1oYys028t73Tf+XJ/B8e0rb1noTmOTZbduEamnFXtRz+fz/KJnBZry6JfRdP2lf5jLLTe7Y7evi57o8kyO6qQ3pa9F1PaUPmI4an3a12b4uO6fJRpWtiAAAAAAAAAAEr0D0PlpNU1p4xs0Gsx7nUf+XF/F8O072bPTnM8lZuO4RpqcU+1PL5fP8L2pUlRioxSUYpKKWxJLYkkWUcGNmZqnMuYeAAAAAAAAAAAA6bZZYW2nKnUipwkmpRaxTR5MRMYl90V1UVRVTOJhSmm+glTR9urS1qlm2vHfKiuU+cf6vHmV96xNHGOTW7fulGoxRXwq8+78J/0Sei6ftK/zGStN7tSb18XPdHkmR3VSG9LXoup7Sh8xHDU+7WuzfFx3T5KNK1sQAAAAAAAABM9CNBKmkDVWrrU7NseO6VZcoco/wBXhzJFmxNfGeSp3DdKNPmijjV5d/4XXY7LCw0406cVCEUlGKWCSLCIiIxDJV11V1TVVOZl3Hr4AAAAAAAAAAAAAAYaxA89gsFO7oOFKChDWlLVWxJyeLwXDaeRTEcIdLl2u5PSrnMvSeuaG9LXoup7Sh8xHDU+7WuzfFx3T5KNK1sQAAAAAAHtui6a18z1LPTlUlsxw82PXKW6J9U0TVOIcb1+3Zp6VycLV0U6MqVgaqWtxrVNjVNL8KD68fPfbguom29NEcauLN6zea7nq2fVjt6/0sFLAlKNkAAAAAAAAAAAAAAAAAAANPpZcX/kdllQ18vWcJKWrr4OMsVsxWO7mc7lHTpwlaPU/wCmuxcxlVV49F9tsv8AhulWXVJ037sv5IdWlrjk0lre9PV7WY+6P2rRe22Tz7LX/tg6i8YYnKbVcdSdRrtNXyrjxx5tfUsdSl51Kqu2nNfFHx0Z7HeLlE8qo8YKdjqVfNpVX2U5v4IdGewm5RHOqPGGwsui9ttfmWWv3wdNeM8D7i1XPU4V63TUc648c+SQXd0X221f4jpUV/VJzfux/k606aueaDd3vT0+zmUwubosstiwlXlO0S5P8On7ieL72zvRpaY58VXf3u9Xwtx0Y8Z8f0m9kssLHBQpwjCC3RilFLuRIiIjhCnrrqrnpVTmXcevkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//Z
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "percona-public", "product_id": {{ .Chart.Name | quote }}, "partner_name": "percona"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Percona Xtradb Cluster Operator
    version: {{ .Values.operator.image.tag | quote }}
    description: |-
      ## Percona is Cloud Native

      The Percona Kubernetes Operator for Percona XtraDB Cluster automates the
      creation, alteration, or deletion of nodes in your cluster environment. It
      can be used to instantiate a new database cluster or to scale an existing
      database cluster. The Operator contains all necessary Kubernetes settings to
      provide a proper and consistent Percona XtraDB Cluster instance.


      Consult the
      [documentation](https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html)
      on the Percona Kubernetes Operator for Percona XtraDB Cluster for complete
      details on capabilities and options.


      ### Supported Features


      * **Scale Your Cluster**  change the `size` parameter to [add or remove members](https://www.percona.com/doc/kubernetes-operator-for-pxc/scaling.html)
      of the cluster. Three is the minimum recommended size for a functioning
      cluster.


      * **Manage Your Users**  [add, remove, or change](https://www.percona.com/doc/kubernetes-operator-for-pxc/users.html)
      the privileges of database users


      * **Automate Your Backups**  [configure cluster backups](https://www.percona.com/doc/kubernetes-operator-for-pxc/backups.html)
      to run on a scheduled basis. Backups are stored on a persistent volume.

      # Support
      Community support is available on [community forum](https://forums.percona.com/categories/kubernetes-operator-percona-xtradb-cluster).
    maintainers:
    - name: Percona
      url: https://github.com/percona/percona-xtradb-cluster-operator
    links:
    - description: 'User Guide: Google Click to Deploy Percona Xtradb Cluster Operator'
      url: https://github.com/percona/percona-helm-charts/blob/master/charts/gcp-marketplace/pxc-operator/README.md
    - description: 'Official documentation for Percona Xtradb Cluster Operator'
      url: https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html
    notes: |-
      # Get authentication credentials for the cluster
      ```shell
      gcloud container clusters get-credentials [CLUSTER_NAME] --zone [CLUSTER_ZONE]
      ```
      where:
      * `[CLUSTER_NAME]` is the name of the cluster for this app
      * `[CLUSTER_ZONE]` is the zone in which the cluster is operating
      For more information, read the [instructions for getting authentication credentials for the cluster](https://cloud.google.com/kubernetes-engine/docs/quickstart#get_authentication_credentials_for_the_cluster).
      # Get the status of the cluster
      By default, the app does not have an external IP address. To get the
      status of the cluster, use `kubectl` to execute `mysqladmin` on a percona mysql client pod:
      ```
      kubectl run -i --rm --tty percona-client --image=percona:{{ .Values.pxc.version | trunc 3 }} --restart=Never -- bash -il
      ```
      Executing this command will open a bash command prompt:
      ```
      If you don't see a command prompt, try pressing enter.
      $
      ```
      Now run mysql tool in the percona-client command shell using the password obtained from the secret:
      ```
      mysql -h {{ .Release.Name }}-haproxy -uroot -p$MYSQL_ROOT_PASSWORD
      ```
  info:
  - name: Percona Xtradb Cluster root password
    type: Reference
    valueFrom:
      secretKeyRef:
        key: root
        name: {{ .Release.Name }}-secrets
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
    - group: apps/v1
      kind: StatefulSet
    - group: apps/v1
      kind: Deployment
    - group: batch/v1
      kind: Job
    - group: v1
      kind: PersistentVolumeClaim
    - group: v1
      kind: Service
    - group: v1
      kind: ConfigMap
    - group: v1
      kind: Secret


