apiVersion: v2
name: pg-operator
description: 'A Helm chart for Deploying the Percona Kubernetes Operator for Percona PostgreSQL'
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/percona/percona-postgresql-operator
maintainers:
  - name: cap1984
    email: ivan.pylypenko@percona.com
  - name: tplavcic
    email: tomislav.plavcic@percona.com
keywords:
  - PostgreSQL
  - Operator
  - Database
  - Postgres
  - SQL
  - RDBMS
